#!/bin/bash
#
# Generate a config directory per simulated node from the templates in config/.
#
#   scripts/make-node-configs.sh 2        # makes nodes/MPMT001 and nodes/MPMT002
#
# One image serves every node; what makes a node distinct is the directory it
# runs in. Only three things actually differ:
#
#   device_name  what ServiceDiscovery advertises, and what the RBU matches
#                against with its case-sensitive "MPMT" prefix compare
#   card_id      what goes in the DAQ header, so decoded data can be traced
#                back to the board it came from
#   mss_url      the node's own mss service
#
# Ports are deliberately left alone. On the bridge every node has its own IP,
# so two nodes can both bind 8888 without colliding - which is the whole point
# of moving off the host network, where the RBU keys connections by ip:port
# and same-host nodes silently collapsed into one.
#
# The UUID is not templated either: DAQInterface generates one on first run
# and saves it at UUID_path, which lands inside the node's own directory. A
# shared UUID would make every node present itself as the same client.

set -euo pipefail

here=$(cd "$(dirname "$0")/.." && pwd)
count=${1:-2}

# card_id is deliberately the module number from the name: MPMT001 is card 1.
# The RBU only ever sees the card id - the device name is not in the data
# messages - so tying the two together lets it derive a provisional PMT id
# straight from the DAQ header, as (card_id - 1) * 19 + channel + 1. MPMT001
# then owns PMTs 1-19, MPMT002 owns 20-38, and so on.
#
# This is a stand-in for the real channel-to-PMT map, which does not exist yet:
# locations in the database is empty (upstream middleman_v2 !15 seeds it) and
# nothing links electronics to a position at all. Override the base only if you
# need to model a specific board numbering.
first_card=${MPMT_FIRST_CARD_ID:-1}

for i in $(seq 1 "$count"); do

  name=$(printf 'MPMT%03d' "$i")
  card=$(( first_card + i - 1 ))
  dir="$here/nodes/$name"

  mkdir -p "$dir"
  cp "$here/config/InterfaceConfig" "$here/config/DataSenderConfig" "$here/config/MSSConfig" "$dir/"

  sed -i "s|^device_name .*|device_name $name                         # generated by scripts/make-node-configs.sh|" "$dir/InterfaceConfig"
  sed -i "s|^card_id .*|card_id $card			      # generated by scripts/make-node-configs.sh|" "$dir/DataSenderConfig"
  sed -i "s|^mss_url .*|mss_url http://${name,,}-mss:8000/rpc   # this node's own mss, by compose service name|" "$dir/MSSConfig"

  # A UUID copied from the template would be shared by every node.
  rm -f "$dir/UUID"

  echo "$name: card_id $card, mss at ${name,,}-mss -> $dir"
done
